version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    volumes:
     - static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    # restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    # sleep для подготовки БД, без него алембик не накатывает миграцию
    command: ["sh", "-c", "sleep 5 && alembic upgrade head && cd /app/src && uvicorn main:app_api --host 0.0.0.0 --port 8000 --reload"]

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_LOG_DESTINATION=stderr
      - POSTGRES_LOGGING_COLLECTOR=on
      - POSTGRES_LOG_DIRECTORY=/var/log/postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
  
volumes:
  static:


