"""tweet_add_array

Revision ID: 4631d57131ef
Revises: fe285cbcce13
Create Date: 2024-06-24 13:55:00.696089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4631d57131ef'
down_revision: Union[str, None] = 'fe285cbcce13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('media_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'media_ids')
    # ### end Alembic commands ###
