"""Relationship tweets medias

Revision ID: 822971d4b26b
Revises: fc4135462e54
Create Date: 2024-06-26 14:55:22.070917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822971d4b26b'
down_revision: Union[str, None] = 'fc4135462e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('tweet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medias', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medias', type_='foreignkey')
    op.drop_column('medias', 'tweet_id')
    # ### end Alembic commands ###
