"""Timestamp_to_tweet

Revision ID: fc4135462e54
Revises: 4631d57131ef
Create Date: 2024-06-25 21:06:47.689742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4135462e54'
down_revision: Union[str, None] = '4631d57131ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweets', 'timestamp')
    # ### end Alembic commands ###
